spring:
  application:
    name: Livraria Tunoda
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

management:
  endpoints:
    web:
      base-path: /api/v1/actuator
      exposure:
        include: health
  endpoint:
    health:
      show-details: never  # segurança - não expor detalhes por padrão