spring:
  application:
    name: Livraria Tunoda
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB:livraria_db}
    username: ${POSTGRES_USER:livraria_user}
    password: ${POSTGRES_PASSWORD:livraria_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    enabled: true

logging:
  level:
    root: INFO
    br.com.iraquitantunoda.livrariatunoda: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      environment: dev
    distribution:
      percentiles-histogram:
        http.server.requests: true
